In [10]:
import numpy as np
a=np.array([0,1,2,3,4])
a


array([0, 1, 2, 3, 4])

In [11]:
(type(a))

numpy.ndarray

In [12]:
a.dtype

dtype('int32')

In [13]:
a.shape

(5,)

In [14]:
a.ndim

1

In [15]:
a.itemsize

4

In [16]:
a.nbytes    #4*5

20

In [17]:
#multidimensional array

In [21]:
a=np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [22]:
a.shape

(2, 4)

In [8]:
import numpy as np
a=np.array([[0,1,2,3],[10,11,12,13]])
a[1,3]=-1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [25]:
a.size

8

In [26]:
a.ndim

2

In [27]:
print(np.__version__)

1.26.4


In [28]:
#zero dimention

In [30]:
import numpy as np
arr=np.array(2)
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

2
1
()
<class 'numpy.ndarray'>
no. of dimension: 0


In [34]:
arr=np.array([2])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

[2]
1
(1,)
<class 'numpy.ndarray'>
no. of dimension: 1


In [33]:
#one dimension
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

[1 2 3 4 5]
5
(5,)
<class 'numpy.ndarray'>
no. of dimension: 1


In [36]:
#2D
arr=np.array([[2],[4]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

[[2]
 [4]]
2
(2, 1)
<class 'numpy.ndarray'>
no. of dimension: 2


In [37]:
arr=np.array([[2,4],[4]]) #number of columns in each row should be same
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [38]:
arr=np.array([[1,2,8],[3,4,9],[5,6,7]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

[[1 2 8]
 [3 4 9]
 [5 6 7]]
9
(3, 3)
<class 'numpy.ndarray'>
no. of dimension: 2


In [39]:
arr=np.array([[2.0,1],[1,2]]) #integers will be converted into float...implicit conversions happen
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('no. of dimension:',nd)

[[2. 1.]
 [1. 2.]]
4
(2, 2)
<class 'numpy.ndarray'>
no. of dimension: 2


In [40]:
#create an array with 5 dimensions and verify it's 5 dimensions
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [41]:
#array indexing
#get first element from then following array:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [10]:
#sum of 3rd and 4th element in an array one dimensional
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [11]:
#2d array of size 2*5 access the second element on first dimension (2nd column 1st row)
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on first dimension:',arr[0,1])

2nd element on first dimension: 2


In [20]:
#3d access 3rd element of the second array of the first array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print()
print(arr[0,1,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

6


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5])
sum=arr[1]+arr[3]
diff=arr[3]-arr[2]
product=arr[2]*arr[2]
div=arr[3]/arr[1]
print(sum)
print(diff)
print(product)
print(div)

6
1
9
2.0


In [23]:
#slicing 1d array
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]


In [29]:
#Slicing 2d  array
#from the second element ,slice elements
#from index 1 to index 4(not included):
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [32]:
#numpy array copy
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=44
print(arr)
print(x)

[44  2  3  4  5]
[1 2 3 4 5]


In [36]:
#create a one dimensional array with12 elements and convert that into 2d array as 4*3 

In [37]:
#reshaping
#convert 1d into 3d
#outermost dimension will have 2 arrays that contains 3 arrays,each with 2 elements
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:

np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [42]:
np.arange(1,5)

array([1, 2, 3, 4])

In [10]:
#elementwise arithmetic operations
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2) 
print(arr1-arr2) 
print(arr1*arr2) 
print(arr1/arr2)
print(arr1@arr2) #actual matrix multiplication
concatenated_arr=np.concatenate((arr1,arr2),axis=0)
#concatenate along rows
print(concatenated_arr)
print()
concatenated_arr=np.concatenate((arr1,arr2),axis=1)
#concatenate along columns
print(concatenated_arr)
print()
arr=np.array([[1,2,3],[4,5,6]])
transposed_arr=arr.transpose() #interchange row elements to column elements and vice-versa
print(transposed_arr)
print()
flattened_arr=arr.flatten() # converts multidimension to single dimension
print(flattened_arr)
print()




[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]



In [11]:
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print('original array')
print(a)
print('checking for a complex number:')
print(np.iscomplex(a)) 
print('checking for a real number:')
print(np.isreal(a))
print('checking for a scalar type:') #is it a single element
print(np.isscalar(3.1)) 
print(np.isscalar([3.1])) #false because it's a list


original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking for a complex number:
[ True False False False False  True]
checking for a real number:
[False  True  True  True  True False]
checking for a scalar type:
True
False


In [14]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [15]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [16]:
arr=np.zeros([2,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
import numpy as np
empty=np.empty((2,3)) #random values
empty

array([[1., 0., 0.],
       [0., 0., 2.]])

In [4]:
#crop yields for 4 farms over 5 seasons(in tons)
import numpy as np
crop_yields=np.array([
    [12.5,13.4,14.4,13.2,15.5],
    [10.1,11.2,10.3,12.4,11.9],
    [15.2,13.4,15.6,16.3,15.1],
    [11.1,10.2,12.1,13.2,11.1]
])
print('Crop yields array(tons):',crop_yields)
print(f'\nShape:{crop_yields.shape}')
print(f'Datatype:{crop_yields.dtype}')
print(f'Total elements:{crop_yields.size}')
print(f'Number of dimensions:{crop_yields.ndim}')
    

    


Crop yields array(tons): [[12.5 13.4 14.4 13.2 15.5]
 [10.1 11.2 10.3 12.4 11.9]
 [15.2 13.4 15.6 16.3 15.1]
 [11.1 10.2 12.1 13.2 11.1]]

Shape:(4, 5)
Datatype:float64
Total elements:20
Number of dimensions:2


In [9]:
import numpy as np
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1) #row
avg_yield_per_season=np.mean(crop_yields,axis=0) #column
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\nTotal production:{total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons') 
print(f'Maximum yield:{max_yield}tons')
print(f'Minimum yield:{min_yield}tons')



Total production:258.2tons
Average per farm:[13.8  11.18 15.12 11.54]tons
Average per season:[12.225 12.05  13.1   13.775 13.4  ]tons
Maximum yield:16.3tons
Minimum yield:10.1tons


In [16]:
best_farm=np.argmax(avg_yield_per_farm) #argmax() does not return the max value itself-it returns where that value is located
worst_farm=np.argmin(avg_yield_per_farm)
print('best farm:',best_farm)
print('worst farm:',worst_farm)
print('\nbest performing farm:farm',best_farm +1)

best farm: 2
worst farm: 1

best performing farm:farm 3


In [20]:
#boolean indexing:find exceptional yields
exceptional=crop_yields>15
print(exceptional)
print('\nExceptional yields(>15):')
print(crop_yields[exceptional])

[[False False False False  True]
 [False False False False False]
 [ True False  True  True  True]
 [False False False False False]]

Exceptional yields(>15):
[15.5 15.2 15.6 16.3 15.1]


In [21]:
#conditional operations:classify yields
categories=np.where(crop_yields>16,'high',
                    np.where(crop_yields>14,'medium','low'))
print('\nyield_categories:')
print(categories)


yield_categories:
[['low' 'low' 'medium' 'low' 'medium']
 ['low' 'low' 'low' 'low' 'low']
 ['medium' 'low' 'medium' 'high' 'medium']
 ['low' 'low' 'low' 'low' 'low']]


In [23]:
print(np.cumsum(crop_yields))

[ 12.5  25.9  40.3  53.5  69.   79.1  90.3 100.6 113.  124.9 140.1 153.5
 169.1 185.4 200.5 211.6 221.8 233.9 247.1 258.2]
